---
title: "Music and Economic Sentiment"
author: "Madhuri Raghunath"
date: "7/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r install_packages, include=FALSE, warning=FALSE}
library(stats)
library(tidyverse)
library(devtools)
library(lubridate)
library(scales)
```

```{r obtain_consumer_sentiment_data, include=FALSE, warning=FALSE}
# import consumer sentiment data
full_consumer_data <- read_csv("tbmics.csv")
# filter to include data from 2006 onwards
cdat <- full_consumer_data %>%
                  filter(YYYY >= 2006)
concat_date <- paste(cdat$Month,cdat$YYYY)
concat_date <- parse_date_time(concat_date, orders = "bY")
cdat <- cdat %>% mutate(concat_date) %>% mutate(id = 1:150)
```

```{r plot_consumer_index, warning=FALSE}
cdat$concat_date <- as.Date(cdat$concat_date)
ggplot(cdat, aes(x=concat_date, y=ICS_ALL)) +
  geom_line(stat = "identity") +
  geom_point() +
  scale_x_date(labels = date_format("%m-%Y")) + 
  xlab("Date") + ylab("ICS")
```

```{r obtain_billboard_data, echo=FALSE, warning=FALSE}
bbdat <- read_csv("bb_charts.csv")
```

```{r install_rspotify, include=FALSE}
install_github("tiagomendesdantas/Rspotify")
```

```{r obtain_spotify_data}
library(Rspotify)
keys <- spotifyOAuth(app_id = "economicsentiments.rmd", client_id = "d180a8b2c34d4cc9bdece7c8f5de7d5a", client_secret = "4cdfdc376ce843e8a39524e6fb29d33e")
```

```{r}
dat <- data.frame(song=character(),
                 song_id=character(), 
                 singer=character(), 
                 stringsAsFactors=FALSE) 

#for (i in 1:nrow(bbdat)) {
#  potential_tracks = searchTrack(bbdat[i,]$song, token = keys)
#  final_track = potential_tracks %>%
#                    filter(display_name == bbdat[i,]$song) %>%
#                    filter(unlist(Map(function(x, y) grepl(x, y), artists, bbdat[i,]$artist))) %>%
#                    slice(1L) %>%
#                    select(display_name, id, artists)
#  dat = rbind(dat, final_track)
#}
```

```{r}
all_songs = data.frame(row.names = NULL)
dat = data.frame(row.names = NULL)
bbdat$clean_artist = NA

for (i in 1:nrow(bbdat)) {
  # Truncate strings to obtain main artist name
  bbdat[i,"clean_artist"] = sub(",.*","",bbdat[i,"artist"]) %>% trimws("right")
  bbdat[i,"clean_artist"] = sub("&.*","",bbdat[i,"clean_artist"]) %>% trimws("right")
  bbdat[i,"clean_artist"] = sub("Featuring.*","",bbdat[i,"clean_artist"]) %>% trimws("right")
}
  # Search for main artist in Spotify
  #potential_artists = searchArtist(bbdat[i,]$clean_artist, token = keys)
  #rbind(dat,potential_artists)

  #final_artist = potential_artists %>%
                    #filter(display_name == bbdat[i,]$clean_artist) %>%
                    #slice(1L) %>% select(potential_artists$id)
  
  # Search for artists' albums
  #potential_albums <- getAlbums(final_artist$id, token = keys)
  
  # Find song match after parsing through all albums
  #for (j in 1:nrow(potential_albums)) {
  #  all_songs = rbind(all_songs, getAlbum(potential_albums[j,]$id, token = keys))
  #}
  
  #all_songs = all_songs %>% 
                #filter(name == bbdat[i,]$song) %>%
                #select(all_songs$id, all_songs$name) %>% slice(1L)
  
  # Find song features
 # features <- getFeatures(all_songs$id, token = keys)
 # dat = all_songs %>% as_tibble() %>% mutate(
  #  features$danceability, features$energy, 
  #  features$loudness, features$tempo, features$valence)
 # dat = as.data.frame(dat)
#}
```

